### ISSUE TITLE
errors about brie-quant

### ISSUE THREAD

**Issue by liuyu988** [huangyh09/brie-tutorials#2]
Hi, Yuanhua

I'm sorry to disturb you for so many times!
When i ran the `brie-quant`, i met a terrible error and i can't understand how to solve it!

 my code:
> brie-quant -i test5/brie_count.h5ad -o test5/brie_quant_cell.h5ad -c test5/cell_note.tsv --interceptMode gene --LRTindex=ALL

my cell_note.tsv: 
I want to detect the differential events between the two celltype.
>  barcodes	celltype	type
> AAACCTGAGAGGACGG-1	0	0
> AAACCTGAGGGATACC-1	0	0
> AAACCTGAGTCCAGGA-1	1	0
> AAACCTGAGTTCGATC-1	1	0

my error:

> Traceback (most recent call last):
>   File "/public2/home/rotation/miniconda3/envs/TFProb/bin/brie-quant", line 8, in <module>
>     sys.exit(main())
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/brie/bin/quant.py", line 219, in main
>     options.batch_size, options.pseudo_count, options.test_base)
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/brie/bin/quant.py", line 42, in quant
>     adata = brie.read_h5ad(in_file)
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 236, in read_h5ad
>     d[k] = read_dataframe(f[k])
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/anndata/_io/h5ad.py", line 301, in read_dataframe
>     return read_elem(group)
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/anndata/_io/specs/registry.py", line 183, in read_elem
>     return _REGISTRY.get_reader(type(elem), get_spec(elem), frozenset(modifiers))(elem)
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/anndata/_io/specs/methods.py", line 523, in read_dataframe
>     {k: read_elem(elem[k]) for k in columns},
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/anndata/_io/specs/methods.py", line 523, in <dictcomp>
>     {k: read_elem(elem[k]) for k in columns},
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/anndata/_io/specs/registry.py", line 183, in read_elem
>     return _REGISTRY.get_reader(type(elem), get_spec(elem), frozenset(modifiers))(elem)
>   File "/public2/home/rotation/miniconda3/envs/TFProb/lib/python3.7/site-packages/anndata/_io/specs/methods.py", line 327, in read_string_array
>     return read_array(d.asstr())
> AttributeError: 'Dataset' object has no attribute 'asstr'

**Comment by liuyu988** [comment]
There seems be to have something wrong in scanpy.read_h5ad().

my version of scanpy is 1.9.1 installing from `pip install -r requirements.txt`.

Would you offer some help for me ? thanks
